apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tekton-pipelines
  name: config-defaults
data:
  # default-timeout-minutes contains the default number of
  # minutes to use for TaskRun and PipelineRun, if none is specified.
  default-timeout-minutes: "60"  # 60 minutes

  # default-service-account contains the default service account name
  # to use for TaskRun and PipelineRun, if none is specified.
  default-service-account: "default"

  # default-managed-by-label-value contains the default value given to the
  # "app.kubernetes.io/managed-by" label applied to all Pods created for
  # TaskRuns. If a user's requested TaskRun specifies another value for this
  # label, the user's request supercedes.
  default-managed-by-label-value: "tekton-pipelines"

  # default-pod-template contains the default pod template to use for
  # TaskRun and PipelineRun. If a pod template is specified on the
  # PipelineRun, the default-pod-template is merged with that one.
  default-pod-template: |
    nodeSelector:
      layer: platform

  # default-task-run-workspace-binding contains the default workspace
  # configuration provided for any Workspaces that a Task declares
  # but that a TaskRun does not explicitly provide.
  default-task-run-workspace-binding: |
    emptyDir: {}

  # default-max-matrix-combinations-count contains the default maximum number
  # of combinations from a Matrix, if none is specified.
  default-max-matrix-combinations-count: "256"
