# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "tarkalabs-terraform"
    encrypt = true
    key     = "serverlessforms/prod/./terraform.tfstate"
    region  = "us-east-1"
  }
}
